extends:
  - [spectral:oas, all]
  #  - ./openapi/spectral/digitalocean.yaml
  - ./openapi/spectral/adidas.yaml
  - "@apisyouwonthate/style-guide"

formats: [oas3]

functionsDir: ./openapi/spectral/functions

rules:
  contact-properties: warn
  operation-singular-tag: warn
  adidas-oas3-response-success-OK: off
