name: bug report
description: File a Bug report.
title: "[Bug]: "
labels: ["triage"]
projects: [SecureElections/2]
assignees:
  - SoGam34
body:
  - type: markdown
    attributes:
      value: |
       Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: examplee-mail@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: Tell us what you see!
      value: "A Bug happened!"
    validations:
      required: true
  - type: dropdown
    id: impact
    attributes:
      label: scopes
      description: how large was the Impact
      options:
      - neglectable 
      - minior 
      - medium 
      - large  
      default: 0
    validations:
      required: true
  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
