name: vulnerability
description: File a vulnerability.
title: "[vulnerability]: "
labels: ["triage"]
projects: [SecureElections/SecureElections/Scrum board"]
assignees:
  - Nasraell
  - SoGam34

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this vulnerability report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: examplee-mail@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Something happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Scope
      description: If you Had to Guess the Scope?
      options:
      - neglectable 
      - minior 
      - medium 
      - lage 
      - Holy Fuck 
      default: 0
    validations:
      required: true
  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
